name: native_pdf_view
description: Flutter Plugin to render PDF files on both Android and iOS devices. Provides a Widget to render the pages using a PageView.
version: 1.0.1
author: Serge Shkurko <sergeshkurko@outlook.com>
homepage: https://github.com/rbcprolabs/native_pdf_view

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.scer.native_pdf_view
    pluginClass: NativePDFViewPlugin

