name: flutter_color
description: Flutter plugin for works with colors schemes like a hex, hsl, xyz and cielab
version: 1.0.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/flutter_color

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.9.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
