name: epub_view
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on dart-epub package.
repository: https://github.com/ScerIO/packages.flutter/tree/main/packages/epub_view
issue_tracker: https://github.com/ScerIO/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+epub_view%22
version: 3.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  epubx: ^3.0.0
  equatable: ^2.0.3
  html: ^0.15.0
  flutter_html: ^3.0.0-alpha.3
  scrollable_positioned_list: ^0.3.2
  collection: ^1.16.0
  universal_file: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

