name: native_pdf_view
description: Flutter plugin to render PDF files on both Android and iOS devices. Provides a Widget to render the pages using a PageView.
version: 2.1.0
author: Serge Shkurko <sergeshkurko@outlook.com>
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_view

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  extended_image: ^0.6.5
  native_pdf_renderer: ^1.6.1

