name: native_pdf_view
description: Flutter plugin to render PDF files on Web, MacOS, Windows, Android and iOS.
repository: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_view
issue_tracker: https://github.com/rbcprolabs/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+native_pdf_view%22
version: 6.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.13.0
  synchronized: ^3.0.0
  pdf_renderer: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# dependency_overrides:
#   pdf_renderer: 
#     path: ../pdf_renderer
