name: native_pdf_view
description: Flutter plugin to render PDF files on Web, MacOS, Android and iOS.
version: 4.0.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_view

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_view:
    git: https://github.com/DevNico/photo_view.git
  synchronized: ^3.0.0
  native_pdf_renderer: 
    path: ../native_pdf_renderer


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
