name: native_pdf_renderer
description: Flutter plugin to render PDF pages as images on Web, MacOS, Android and iOS.
version: 2.4.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_renderer

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  uuid: ^2.2.2
  image: ^2.1.19
  js: ^0.6.2
  meta: ^1.1.8
  extension: ^0.1.1
  synchronized: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.pdf.renderer
        pluginClass: NativePDFRendererPlugin
      ios:
        pluginClass: NativePDFRendererPlugin
      macos:
        pluginClass: NativePdfRendererPlugin
      web:
        fileName: src/web/native_pdf_renderer_plugin.dart
        pluginClass: NativePdfRendererPlugin
