name: native_pdf_renderer
description: Flutter plugin to render PDF pages as images on Web, MacOS, Android and iOS.
version: 3.1.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_renderer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  device_info: ^2.0.0
  uuid: ^3.0.1
  image: ^3.0.1
  js: ^0.6.3
  meta: ^1.3.0
  extension: ^0.2.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.native_pdf_renderer
        pluginClass: NativePdfRendererPlugin
      ios:
        pluginClass: NativePdfRendererPlugin
      macos:
        pluginClass: NativePdfRendererPlugin
      windows:
        pluginClass: NativePdfRendererPlugin
      web:
        pluginClass: NativePdfRendererPlugin
        fileName: src/web/native_pdf_renderer_plugin.dart
