name: native_pdf_renderer
description: Flutter plugin to render PDF pages as images on Web, MacOS, Windows, Android and iOS.
repository: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_renderer
issue_tracker: https://github.com/rbcprolabs/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+native_pdf_renderer%22
version: 5.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf_renderer: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
