name: explorer
description: 'Universal explorer UI for navigate files, ftp, etc. Support custom providers and any platforms c:'
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/explorer
issue_tracker: https://github.com/rbcprolabs/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+explorer%22
version: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter     
  intl: ^0.17.0  
  flutter_breadcrumb: ^1.0.1
  auto_animated: ^3.0.0
  sliver_tools: ^0.2.5
  universal_platform: ^1.0.0+1
  path: ^1.8.0
  meta: ^1.3.0
  io: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#   intl_translation: ^0.17.10+1

# dependency_overrides:
#   intl: ^0.17.0 

scripts:
  i18n_to_arb: flutter pub run intl_translation:extract_to_arb --output-dir=locales lib/src/i18n/string_resources.dart
  i18n_from_arb: flutter pub run intl_translation:generate_from_arb lib/src/i18n/string_resources.dart locales/*.arb --output-dir=lib/src/i18n/messages
