name: native_color
description: Flutter plugin for works with colors schemes like a hex, hsl, xyz and cielab
version: 1.0.0
author: Serge Shkurko <sergeshkurko@outlook.com>
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_color

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.5.0
  flutter_test:
    sdk: flutter
