name: pdfx
description: Flutter plugin to render & show PDF pages as images on Web, MacOS, Windows, Android and iOS.
repository: https://github.com/ScerIO/packages.flutter/tree/main/packages/pdfx
issue_tracker: https://github.com/ScerIO/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+pdfx%22
version: 2.3.0

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  js: ^0.6.4
  device_info_plus: ^9.0.0
  uuid: ^3.0.6
  meta: ^1.7.0
  extension: ^0.6.0
  synchronized: ^3.0.0+2
  universal_platform: ^1.0.0+1
  photo_view: ^0.14.0
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^4.2.0

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.pdfx
        pluginClass: PdfxPlugin
      ios:
        pluginClass: PdfxPlugin
      macos:
        pluginClass: PdfxPlugin
      windows:
        pluginClass: PdfxPlugin
      web:
        pluginClass: PdfxPlugin
        fileName: src/renderer/web/pdfx_plugin.dart
