name: auto_animated
description: Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.
version: 3.0.1
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/auto_animated

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
